### ISSUE TITLE
Change more cluster parameters to pass-through

### ISSUE THREAD

**Issue by JoshKarpel** [JoshKarpel/dask-chtc#1]
Right now, the worker parameters are specified using high-level switches or not at all. Users will want to give individualized worker resource requests, for example, as well as individualized ``job_extra`` so they can get GPUs.

I still like the idea of a small abstraction layer sitting on top of `dask_jobqueue.HTCondorCluster`, mainly to rename arguments to language that will be more familiar to CHTC users. Things that we know users will need to pass in like the scheduler and dashboard ports can also be bumped up to first-class arguments.

I'm considering boosting GPULab options up to first-class as well, i.e., `request_gpus = 1` automatically triggers `+WantGPULab`, and defaults to short job length.

**Comment by bbockelm** [comment]
I assume this also implies switching from a method that creates an object to a subclass?  While some of the high-level aspects are really nice, I can see where the current approach would be painful for a user to customize...

**Comment by JoshKarpel** [comment]
Yes, especially if we're also shipping a wrapper script #2
